# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_layout.ui'
#
# Created: Tue Mar 26 12:40:37 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 664)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.grid_delay_properties = QtGui.QGridLayout()
        self.grid_delay_properties.setObjectName("grid_delay_properties")
        self.box_word_select = QtGui.QDoubleSpinBox(Dialog)
        self.box_word_select.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.box_word_select.setMaximum(1.0)
        self.box_word_select.setSingleStep(0.05)
        self.box_word_select.setProperty("value", 0.9)
        self.box_word_select.setObjectName("box_word_select")
        self.grid_delay_properties.addWidget(self.box_word_select, 16, 1, 1, 1)
        self.label_seconds_delay = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.label_seconds_delay.setFont(font)
        self.label_seconds_delay.setObjectName("label_seconds_delay")
        self.grid_delay_properties.addWidget(self.label_seconds_delay, 2, 0, 1, 1)
        self.box_seconds_delay = QtGui.QDoubleSpinBox(Dialog)
        self.box_seconds_delay.setDecimals(3)
        self.box_seconds_delay.setMinimum(-60.0)
        self.box_seconds_delay.setMaximum(60.0)
        self.box_seconds_delay.setSingleStep(0.05)
        self.box_seconds_delay.setProperty("value", 0.2)
        self.box_seconds_delay.setObjectName("box_seconds_delay")
        self.grid_delay_properties.addWidget(self.box_seconds_delay, 2, 1, 1, 1)
        self.label_deviation = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.label_deviation.setFont(font)
        self.label_deviation.setObjectName("label_deviation")
        self.grid_delay_properties.addWidget(self.label_deviation, 3, 0, 1, 1)
        self.box_click_dev = QtGui.QDoubleSpinBox(Dialog)
        self.box_click_dev.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.box_click_dev.setDecimals(3)
        self.box_click_dev.setMinimum(0.01)
        self.box_click_dev.setMaximum(1000.0)
        self.box_click_dev.setSingleStep(0.01)
        self.box_click_dev.setProperty("value", 0.05)
        self.box_click_dev.setObjectName("box_click_dev")
        self.grid_delay_properties.addWidget(self.box_click_dev, 3, 1, 1, 1)
        self.box_enable_learning = QtGui.QCheckBox(Dialog)
        self.box_enable_learning.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.box_enable_learning.setChecked(True)
        self.box_enable_learning.setObjectName("box_enable_learning")
        self.grid_delay_properties.addWidget(self.box_enable_learning, 4, 0, 1, 1)
        self.box_learning_rate = QtGui.QDoubleSpinBox(Dialog)
        self.box_learning_rate.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.box_learning_rate.setMaximum(1.0)
        self.box_learning_rate.setSingleStep(0.05)
        self.box_learning_rate.setProperty("value", 0.3)
        self.box_learning_rate.setObjectName("box_learning_rate")
        self.grid_delay_properties.addWidget(self.box_learning_rate, 4, 1, 1, 1)
        self.label_delay = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_delay.setFont(font)
        self.label_delay.setStatusTip("")
        self.label_delay.setObjectName("label_delay")
        self.grid_delay_properties.addWidget(self.label_delay, 1, 0, 1, 1)
        self.label_fp_rate = QtGui.QLabel(Dialog)
        self.label_fp_rate.setObjectName("label_fp_rate")
        self.grid_delay_properties.addWidget(self.label_fp_rate, 8, 0, 1, 1)
        self.box_fp_rate = QtGui.QDoubleSpinBox(Dialog)
        self.box_fp_rate.setDecimals(4)
        self.box_fp_rate.setMinimum(0.0)
        self.box_fp_rate.setMaximum(3.0)
        self.box_fp_rate.setSingleStep(0.01)
        self.box_fp_rate.setProperty("value", 0.25)
        self.box_fp_rate.setObjectName("box_fp_rate")
        self.grid_delay_properties.addWidget(self.box_fp_rate, 8, 1, 1, 1)
        self.label_fr = QtGui.QLabel(Dialog)
        self.label_fr.setObjectName("label_fr")
        self.grid_delay_properties.addWidget(self.label_fr, 9, 0, 1, 1)
        self.label_switch_noise = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_switch_noise.setFont(font)
        self.label_switch_noise.setObjectName("label_switch_noise")
        self.grid_delay_properties.addWidget(self.label_switch_noise, 6, 0, 1, 1)
        self.label_word_select_thresh = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(50)
        font.setBold(False)
        self.label_word_select_thresh.setFont(font)
        self.label_word_select_thresh.setObjectName("label_word_select_thresh")
        self.grid_delay_properties.addWidget(self.label_word_select_thresh, 16, 0, 1, 1)
        self.label_word_select = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_word_select.setFont(font)
        self.label_word_select.setObjectName("label_word_select")
        self.grid_delay_properties.addWidget(self.label_word_select, 15, 0, 1, 1)
        self.label_error_correct = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_error_correct.setFont(font)
        self.label_error_correct.setObjectName("label_error_correct")
        self.grid_delay_properties.addWidget(self.label_error_correct, 10, 0, 1, 1)
        self.label_undo_last = QtGui.QLabel(Dialog)
        self.label_undo_last.setObjectName("label_undo_last")
        self.grid_delay_properties.addWidget(self.label_undo_last, 11, 0, 1, 1)
        self.box_undo = QtGui.QSpinBox(Dialog)
        self.box_undo.setMinimum(3)
        self.box_undo.setMaximum(100)
        self.box_undo.setSingleStep(1)
        self.box_undo.setProperty("value", 4)
        self.box_undo.setObjectName("box_undo")
        self.grid_delay_properties.addWidget(self.box_undo, 11, 1, 1, 1)
        self.label_program_status = QtGui.QLabel(Dialog)
        self.label_program_status.setObjectName("label_program_status")
        self.grid_delay_properties.addWidget(self.label_program_status, 12, 0, 1, 1)
        self.box_prog_status = QtGui.QSpinBox(Dialog)
        self.box_prog_status.setMinimum(1)
        self.box_prog_status.setMaximum(10)
        self.box_prog_status.setProperty("value", 2)
        self.box_prog_status.setObjectName("box_prog_status")
        self.grid_delay_properties.addWidget(self.box_prog_status, 12, 1, 1, 1)
        self.label_restart_word = QtGui.QLabel(Dialog)
        self.label_restart_word.setObjectName("label_restart_word")
        self.grid_delay_properties.addWidget(self.label_restart_word, 13, 0, 1, 1)
        self.box_restart_word = QtGui.QSpinBox(Dialog)
        self.box_restart_word.setMinimum(2)
        self.box_restart_word.setMaximum(2000)
        self.box_restart_word.setProperty("value", 6)
        self.box_restart_word.setObjectName("box_restart_word")
        self.grid_delay_properties.addWidget(self.box_restart_word, 13, 1, 1, 1)
        self.label_switch_off = QtGui.QLabel(Dialog)
        self.label_switch_off.setObjectName("label_switch_off")
        self.grid_delay_properties.addWidget(self.label_switch_off, 14, 0, 1, 1)
        self.box_shut_down = QtGui.QSpinBox(Dialog)
        self.box_shut_down.setMinimum(4)
        self.box_shut_down.setMaximum(2000)
        self.box_shut_down.setProperty("value", 2000)
        self.box_shut_down.setObjectName("box_shut_down")
        self.grid_delay_properties.addWidget(self.box_shut_down, 14, 1, 1, 1)
        self.label_config_settings = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_config_settings.setFont(font)
        self.label_config_settings.setObjectName("label_config_settings")
        self.grid_delay_properties.addWidget(self.label_config_settings, 17, 0, 1, 1)
        self.label_file_length = QtGui.QLabel(Dialog)
        self.label_file_length.setObjectName("label_file_length")
        self.grid_delay_properties.addWidget(self.label_file_length, 21, 0, 1, 1)
        self.box_file_length = QtGui.QDoubleSpinBox(Dialog)
        self.box_file_length.setSingleStep(0.05)
        self.box_file_length.setProperty("value", 0.21)
        self.box_file_length.setObjectName("box_file_length")
        self.grid_delay_properties.addWidget(self.box_file_length, 21, 1, 1, 1)
        self.box_learn_delay = QtGui.QCheckBox(Dialog)
        self.box_learn_delay.setChecked(True)
        self.box_learn_delay.setObjectName("box_learn_delay")
        self.grid_delay_properties.addWidget(self.box_learn_delay, 2, 2, 1, 1)
        self.box_learn_std = QtGui.QCheckBox(Dialog)
        self.box_learn_std.setChecked(True)
        self.box_learn_std.setObjectName("box_learn_std")
        self.grid_delay_properties.addWidget(self.box_learn_std, 3, 2, 1, 1)
        self.box_learn_fp = QtGui.QCheckBox(Dialog)
        self.box_learn_fp.setChecked(False)
        self.box_learn_fp.setObjectName("box_learn_fp")
        self.grid_delay_properties.addWidget(self.box_learn_fp, 8, 2, 1, 1)
        self.box_learn_fr = QtGui.QCheckBox(Dialog)
        self.box_learn_fr.setChecked(False)
        self.box_learn_fr.setObjectName("box_learn_fr")
        self.grid_delay_properties.addWidget(self.box_learn_fr, 9, 2, 1, 1)
        self.label_channels = QtGui.QLabel(Dialog)
        self.label_channels.setObjectName("label_channels")
        self.grid_delay_properties.addWidget(self.label_channels, 18, 0, 1, 1)
        self.box_channels = QtGui.QComboBox(Dialog)
        self.box_channels.setMaxVisibleItems(14)
        self.box_channels.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.box_channels.setObjectName("box_channels")
        self.box_channels.addItem("")
        self.box_channels.addItem("")
        self.box_channels.addItem("")
        self.box_channels.addItem("")
        self.box_channels.addItem("")
        self.grid_delay_properties.addWidget(self.box_channels, 18, 1, 1, 1)
        self.button_default = QtGui.QPushButton(Dialog)
        self.button_default.setObjectName("button_default")
        self.grid_delay_properties.addWidget(self.button_default, 0, 0, 1, 1)
        self.box_fr = QtGui.QDoubleSpinBox(Dialog)
        self.box_fr.setProperty("value", 5.0)
        self.box_fr.setObjectName("box_fr")
        self.grid_delay_properties.addWidget(self.box_fr, 9, 1, 1, 1)
        self.button_gauss = QtGui.QPushButton(Dialog)
        self.button_gauss.setObjectName("button_gauss")
        self.grid_delay_properties.addWidget(self.button_gauss, 5, 0, 1, 1)
        self.label_end_delay = QtGui.QLabel(Dialog)
        self.label_end_delay.setObjectName("label_end_delay")
        self.grid_delay_properties.addWidget(self.label_end_delay, 22, 0, 1, 1)
        self.box_end_delay = QtGui.QDoubleSpinBox(Dialog)
        self.box_end_delay.setSingleStep(0.1)
        self.box_end_delay.setProperty("value", 0.3)
        self.box_end_delay.setObjectName("box_end_delay")
        self.grid_delay_properties.addWidget(self.box_end_delay, 22, 1, 1, 1)
        self.gridLayout.addLayout(self.grid_delay_properties, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.box_channels.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Settings Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_seconds_delay.setToolTip(QtGui.QApplication.translate("Dialog", "The average click delay, measured in seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.label_seconds_delay.setText(QtGui.QApplication.translate("Dialog", "Average (seconds)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deviation.setToolTip(QtGui.QApplication.translate("Dialog", "The standard deviation of click delay measured in seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deviation.setText(QtGui.QApplication.translate("Dialog", "Deviation (seconds)", None, QtGui.QApplication.UnicodeUTF8))
        self.box_enable_learning.setToolTip(QtGui.QApplication.translate("Dialog", "Adapt the click distribution according to previous word selections", None, QtGui.QApplication.UnicodeUTF8))
        self.box_enable_learning.setText(QtGui.QApplication.translate("Dialog", "Learning rate (0.0 to 1.0)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_delay.setToolTip(QtGui.QApplication.translate("Dialog", "Click visualisation settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_delay.setText(QtGui.QApplication.translate("Dialog", "Click-time delay:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fp_rate.setText(QtGui.QApplication.translate("Dialog", "Average number of false \n"
"positives per minute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fr.setText(QtGui.QApplication.translate("Dialog", "Average percentage \n"
"false negatives (1-100)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_switch_noise.setText(QtGui.QApplication.translate("Dialog", "Switch Noise:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_word_select_thresh.setToolTip(QtGui.QApplication.translate("Dialog", "A word will be selected if its probability is above this value.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_word_select_thresh.setText(QtGui.QApplication.translate("Dialog", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_word_select.setToolTip(QtGui.QApplication.translate("Dialog", "The speed at which the next letter will be displayed/pronounced.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_word_select.setText(QtGui.QApplication.translate("Dialog", "Word selection:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_error_correct.setText(QtGui.QApplication.translate("Dialog", "Error Correction:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_undo_last.setToolTip(QtGui.QApplication.translate("Dialog", "The number of clicks that will immediately result in an undo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_undo_last.setText(QtGui.QApplication.translate("Dialog", "Undo last letter \n"
"(number of clicks)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_program_status.setText(QtGui.QApplication.translate("Dialog", "Read program status \n"
"(number of alphabet repetions)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_restart_word.setText(QtGui.QApplication.translate("Dialog", "New word \n"
"(number of alphabet repetitions)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_switch_off.setText(QtGui.QApplication.translate("Dialog", "Shut down \n"
"(number of alphabet repetions)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_config_settings.setText(QtGui.QApplication.translate("Dialog", "Speed & Channel Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_file_length.setText(QtGui.QApplication.translate("Dialog", "File length (seconds)", None, QtGui.QApplication.UnicodeUTF8))
        self.box_learn_delay.setText(QtGui.QApplication.translate("Dialog", "Learn", None, QtGui.QApplication.UnicodeUTF8))
        self.box_learn_std.setText(QtGui.QApplication.translate("Dialog", "Learn", None, QtGui.QApplication.UnicodeUTF8))
        self.box_learn_fp.setText(QtGui.QApplication.translate("Dialog", "Learn", None, QtGui.QApplication.UnicodeUTF8))
        self.box_learn_fr.setText(QtGui.QApplication.translate("Dialog", "Learn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_channels.setText(QtGui.QApplication.translate("Dialog", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.box_channels.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.box_channels.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.box_channels.setItemText(2, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.box_channels.setItemText(3, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.box_channels.setItemText(4, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.button_default.setText(QtGui.QApplication.translate("Dialog", "Load Default Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gauss.setText(QtGui.QApplication.translate("Dialog", "Set Distribution to Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_delay.setText(QtGui.QApplication.translate("Dialog", "End delay (seconds)", None, QtGui.QApplication.UnicodeUTF8))

