# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticker_layout.ui'
#
# Created: Tue Mar 26 12:40:36 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 808)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 500))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1013, 0))
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_instructions_title = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_instructions_title.sizePolicy().hasHeightForWidth())
        self.label_instructions_title.setSizePolicy(sizePolicy)
        self.label_instructions_title.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setBold(True)
        self.label_instructions_title.setFont(font)
        self.label_instructions_title.setObjectName("label_instructions_title")
        self.gridLayout_6.addWidget(self.label_instructions_title, 0, 0, 1, 1)
        self.label_instructions = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_instructions.sizePolicy().hasHeightForWidth())
        self.label_instructions.setSizePolicy(sizePolicy)
        self.label_instructions.setMinimumSize(QtCore.QSize(500, 50))
        self.label_instructions.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(18)
        self.label_instructions.setFont(font)
        self.label_instructions.setProperty("cursor", QtCore.Qt.IBeamCursor)
        self.label_instructions.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_instructions.setToolTip("")
        self.label_instructions.setReadOnly(False)
        self.label_instructions.setObjectName("label_instructions")
        self.gridLayout_6.addWidget(self.label_instructions, 4, 0, 1, 1)
        self.label_word_output = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.label_word_output.sizePolicy().hasHeightForWidth())
        self.label_word_output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setBold(True)
        self.label_word_output.setFont(font)
        self.label_word_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_word_output.setObjectName("label_word_output")
        self.gridLayout_6.addWidget(self.label_word_output, 7, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.channel_names = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_names.sizePolicy().hasHeightForWidth())
        self.channel_names.setSizePolicy(sizePolicy)
        self.channel_names.setMinimumSize(QtCore.QSize(217, 211))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.channel_names.setFont(font)
        self.channel_names.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.channel_names.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.channel_names.setObjectName("channel_names")
        self.gridLayout_5.addWidget(self.channel_names, 2, 0, 1, 1)
        self.label_channel_names = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setBold(True)
        self.label_channel_names.setFont(font)
        self.label_channel_names.setObjectName("label_channel_names")
        self.gridLayout_5.addWidget(self.label_channel_names, 1, 0, 1, 1)
        self.label_letter_likelihoods = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_letter_likelihoods.sizePolicy().hasHeightForWidth())
        self.label_letter_likelihoods.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_letter_likelihoods.setFont(font)
        self.label_letter_likelihoods.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_letter_likelihoods.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_letter_likelihoods.setLineWidth(1)
        self.label_letter_likelihoods.setTextFormat(QtCore.Qt.PlainText)
        self.label_letter_likelihoods.setObjectName("label_letter_likelihoods")
        self.gridLayout_5.addWidget(self.label_letter_likelihoods, 1, 1, 1, 1)
        self.label_click_distribution = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setBold(True)
        self.label_click_distribution.setFont(font)
        self.label_click_distribution.setObjectName("label_click_distribution")
        self.gridLayout_5.addWidget(self.label_click_distribution, 1, 4, 1, 1)
        self.best_words_disp = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.best_words_disp.sizePolicy().hasHeightForWidth())
        self.best_words_disp.setSizePolicy(sizePolicy)
        self.best_words_disp.setMinimumSize(QtCore.QSize(170, 211))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        self.best_words_disp.setFont(font)
        self.best_words_disp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.best_words_disp.setLineWidth(3)
        self.best_words_disp.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.best_words_disp.setObjectName("best_words_disp")
        self.gridLayout_5.addWidget(self.best_words_disp, 2, 2, 1, 1)
        self.label_best_words = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_best_words.sizePolicy().hasHeightForWidth())
        self.label_best_words.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setBold(True)
        self.label_best_words.setFont(font)
        self.label_best_words.setObjectName("label_best_words")
        self.gridLayout_5.addWidget(self.label_best_words, 1, 2, 1, 1)
        self.alphabet_likelihood_view = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphabet_likelihood_view.sizePolicy().hasHeightForWidth())
        self.alphabet_likelihood_view.setSizePolicy(sizePolicy)
        self.alphabet_likelihood_view.setMinimumSize(QtCore.QSize(310, 211))
        self.alphabet_likelihood_view.setMaximumSize(QtCore.QSize(320, 211))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.alphabet_likelihood_view.setFont(font)
        self.alphabet_likelihood_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.alphabet_likelihood_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alphabet_likelihood_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alphabet_likelihood_view.setObjectName("alphabet_likelihood_view")
        self.gridLayout_5.addWidget(self.alphabet_likelihood_view, 2, 1, 1, 1)
        self.click_distribution_view = QtGui.QWidget(self.centralwidget)
        self.click_distribution_view.setMinimumSize(QtCore.QSize(500, 211))
        self.click_distribution_view.setObjectName("click_distribution_view")
        self.gridLayout_5.addWidget(self.click_distribution_view, 2, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 9, 0, 1, 7)
        self.selected_words_disp = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.selected_words_disp.sizePolicy().hasHeightForWidth())
        self.selected_words_disp.setSizePolicy(sizePolicy)
        self.selected_words_disp.setMinimumSize(QtCore.QSize(500, 80))
        self.selected_words_disp.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        self.selected_words_disp.setFont(font)
        self.selected_words_disp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.selected_words_disp.setToolTip("")
        self.selected_words_disp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.selected_words_disp.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.selected_words_disp.setObjectName("selected_words_disp")
        self.gridLayout_6.addWidget(self.selected_words_disp, 8, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.clear_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_button.sizePolicy().hasHeightForWidth())
        self.clear_button.setSizePolicy(sizePolicy)
        self.clear_button.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setBold(True)
        self.clear_button.setFont(font)
        self.clear_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clear_button.setCheckable(False)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 2, 0, 1, 1)
        self.scrollbar_letter_speed = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollbar_letter_speed.sizePolicy().hasHeightForWidth())
        self.scrollbar_letter_speed.setSizePolicy(sizePolicy)
        self.scrollbar_letter_speed.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollbar_letter_speed.setMinimum(50)
        self.scrollbar_letter_speed.setMaximum(95)
        self.scrollbar_letter_speed.setPageStep(1)
        self.scrollbar_letter_speed.setProperty("value", 65)
        self.scrollbar_letter_speed.setOrientation(QtCore.Qt.Horizontal)
        self.scrollbar_letter_speed.setObjectName("scrollbar_letter_speed")
        self.gridLayout.addWidget(self.scrollbar_letter_speed, 5, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_letter_speed = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_letter_speed.setFont(font)
        self.label_letter_speed.setObjectName("label_letter_speed")
        self.gridLayout_3.addWidget(self.label_letter_speed, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.button_pause = QtGui.QPushButton(self.centralwidget)
        self.button_pause.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setBold(True)
        self.button_pause.setFont(font)
        self.button_pause.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_pause.setCheckable(True)
        self.button_pause.setObjectName("button_pause")
        self.gridLayout.addWidget(self.button_pause, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 4, 6, 5, 1)
        self.phrase_disp = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase_disp.sizePolicy().hasHeightForWidth())
        self.phrase_disp.setSizePolicy(sizePolicy)
        self.phrase_disp.setMinimumSize(QtCore.QSize(700, 50))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(18)
        self.phrase_disp.setFont(font)
        self.phrase_disp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.phrase_disp.setStyleSheet("border-style:ridge;\n"
"border-color: rgb(255, 92, 144);\n"
"border-width:5px;\n"
"")
        self.phrase_disp.setObjectName("phrase_disp")
        self.gridLayout_6.addWidget(self.phrase_disp, 6, 0, 1, 1)
        self.label_phrases = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.label_phrases.sizePolicy().hasHeightForWidth())
        self.label_phrases.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setWeight(75)
        font.setBold(True)
        self.label_phrases.setFont(font)
        self.label_phrases.setObjectName("label_phrases")
        self.gridLayout_6.addWidget(self.label_phrases, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuControl = QtGui.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.alphabet_widget_display = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphabet_widget_display.sizePolicy().hasHeightForWidth())
        self.alphabet_widget_display.setSizePolicy(sizePolicy)
        self.alphabet_widget_display.setMinimumSize(QtCore.QSize(1200, 235))
        self.alphabet_widget_display.setObjectName("alphabet_widget_display")
        self.alphabet_widget = QtGui.QWidget()
        self.alphabet_widget.setObjectName("alphabet_widget")
        self.alphabet_view = QtGui.QGraphicsView(self.alphabet_widget)
        self.alphabet_view.setGeometry(QtCore.QRect(10, 0, 1000, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphabet_view.sizePolicy().hasHeightForWidth())
        self.alphabet_view.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.alphabet_view.setFont(font)
        self.alphabet_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.alphabet_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alphabet_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alphabet_view.setObjectName("alphabet_view")
        self.alphabet_widget_display.setWidget(self.alphabet_widget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.alphabet_widget_display)
        self.edit_alphabet = QtGui.QAction(MainWindow)
        self.edit_alphabet.setObjectName("edit_alphabet")
        self.action_click_selections = QtGui.QAction(MainWindow)
        self.action_click_selections.setCheckable(True)
        self.action_click_selections.setChecked(True)
        self.action_click_selections.setObjectName("action_click_selections")
        self.action_click_distribution = QtGui.QAction(MainWindow)
        self.action_click_distribution.setCheckable(True)
        self.action_click_distribution.setChecked(True)
        self.action_click_distribution.setObjectName("action_click_distribution")
        self.action_best_words = QtGui.QAction(MainWindow)
        self.action_best_words.setCheckable(True)
        self.action_best_words.setChecked(True)
        self.action_best_words.setObjectName("action_best_words")
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setCheckable(False)
        self.action_open.setEnabled(True)
        self.action_open.setObjectName("action_open")
        self.action_letter_likelihoods = QtGui.QAction(MainWindow)
        self.action_letter_likelihoods.setCheckable(True)
        self.action_letter_likelihoods.setChecked(True)
        self.action_letter_likelihoods.setObjectName("action_letter_likelihoods")
        self.action_minimum_view = QtGui.QAction(MainWindow)
        self.action_minimum_view.setCheckable(True)
        self.action_minimum_view.setChecked(False)
        self.action_minimum_view.setObjectName("action_minimum_view")
        self.action_dictionary = QtGui.QAction(MainWindow)
        self.action_dictionary.setCheckable(False)
        self.action_dictionary.setObjectName("action_dictionary")
        self.action_save = QtGui.QAction(MainWindow)
        self.action_save.setCheckable(False)
        self.action_save.setEnabled(True)
        self.action_save.setObjectName("action_save")
        self.action_close = QtGui.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_alphabet = QtGui.QAction(MainWindow)
        self.action_alphabet.setCheckable(True)
        self.action_alphabet.setChecked(True)
        self.action_alphabet.setObjectName("action_alphabet")
        self.actionB = QtGui.QAction(MainWindow)
        self.actionB.setObjectName("actionB")
        self.action_volume = QtGui.QAction(MainWindow)
        self.action_volume.setObjectName("action_volume")
        self.action_settings = QtGui.QAction(MainWindow)
        self.action_settings.setCheckable(False)
        self.action_settings.setObjectName("action_settings")
        self.action_space_bar = QtGui.QAction(MainWindow)
        self.action_space_bar.setCheckable(True)
        self.action_space_bar.setChecked(True)
        self.action_space_bar.setObjectName("action_space_bar")
        self.action_port = QtGui.QAction(MainWindow)
        self.action_port.setCheckable(True)
        self.action_port.setChecked(True)
        self.action_port.setObjectName("action_port")
        self.action_about_ticker = QtGui.QAction(MainWindow)
        self.action_about_ticker.setObjectName("action_about_ticker")
        self.action_clear = QtGui.QAction(MainWindow)
        self.action_clear.setObjectName("action_clear")
        self.action_calibrate = QtGui.QAction(MainWindow)
        self.action_calibrate.setCheckable(True)
        self.action_calibrate.setChecked(True)
        self.action_calibrate.setObjectName("action_calibrate")
        self.action_practise = QtGui.QAction(MainWindow)
        self.action_practise.setCheckable(True)
        self.action_practise.setObjectName("action_practise")
        self.action_tutorial = QtGui.QAction(MainWindow)
        self.action_tutorial.setCheckable(True)
        self.action_tutorial.setVisible(False)
        self.action_tutorial.setObjectName("action_tutorial")
        self.action_inc_phrases = QtGui.QAction(MainWindow)
        self.action_inc_phrases.setCheckable(True)
        self.action_inc_phrases.setChecked(False)
        self.action_inc_phrases.setVisible(False)
        self.action_inc_phrases.setObjectName("action_inc_phrases")
        self.action_fast_mode = QtGui.QAction(MainWindow)
        self.action_fast_mode.setCheckable(True)
        self.action_fast_mode.setChecked(True)
        self.action_fast_mode.setObjectName("action_fast_mode")
        self.action_clear_2 = QtGui.QAction(MainWindow)
        self.action_clear_2.setObjectName("action_clear_2")
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_save)
        self.menuFile.addAction(self.action_close)
        self.menuEdit.addAction(self.action_dictionary)
        self.menuEdit.addAction(self.action_volume)
        self.menuEdit.addAction(self.action_settings)
        self.menuView.addAction(self.action_alphabet)
        self.menuControl.addAction(self.action_space_bar)
        self.menuControl.addAction(self.action_port)
        self.menuHelp.addAction(self.action_about_ticker)
        self.menuMode.addAction(self.action_calibrate)
        self.menuMode.addAction(self.action_fast_mode)
        self.menuMode.addAction(self.action_practise)
        self.menuMode.addAction(self.action_tutorial)
        self.menuMode.addAction(self.action_inc_phrases)
        self.menuDisplay.addAction(self.action_clear_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Ticker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_instructions_title.setToolTip(QtGui.QApplication.translate("MainWindow", "Visual instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_instructions_title.setText(QtGui.QApplication.translate("MainWindow", "Instructions:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_instructions.setStyleSheet(QtGui.QApplication.translate("MainWindow", "border-style:ridge;\n"
"border-color: rgb(92, 114, 255);\n"
"border-width:5px;\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_word_output.setToolTip(QtGui.QApplication.translate("MainWindow", "Word selections are displayed here", None, QtGui.QApplication.UnicodeUTF8))
        self.label_word_output.setText(QtGui.QApplication.translate("MainWindow", "Output sentences:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_channel_names.setToolTip(QtGui.QApplication.translate("MainWindow", "Names of the people reading different parts of the alphabet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_channel_names.setText(QtGui.QApplication.translate("MainWindow", "Names:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_letter_likelihoods.setToolTip(QtGui.QApplication.translate("MainWindow", "After a click the more likely letters will be darker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_letter_likelihoods.setText(QtGui.QApplication.translate("MainWindow", "Letter likelihoods:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_click_distribution.setToolTip(QtGui.QApplication.translate("MainWindow", "Visualisation of click delay distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_click_distribution.setText(QtGui.QApplication.translate("MainWindow", "Click distribution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_best_words.setToolTip(QtGui.QApplication.translate("MainWindow", "Display of most probable words in dictionary.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_best_words.setText(QtGui.QApplication.translate("MainWindow", "Most probable words:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_words_disp.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_button.setText(QtGui.QApplication.translate("MainWindow", "Restart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_letter_speed.setToolTip(QtGui.QApplication.translate("MainWindow", "Sound overlap, if=0.0 all voice will speak simultaneously.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_letter_speed.setText(QtGui.QApplication.translate("MainWindow", "Speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_pause.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.label_phrases.setText(QtGui.QApplication.translate("MainWindow", "Phrases:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuControl.setTitle(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDisplay.setTitle(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.alphabet_widget_display.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tuning in with visual assistance", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_alphabet.setText(QtGui.QApplication.translate("MainWindow", "Alphabet", None, QtGui.QApplication.UnicodeUTF8))
        self.action_click_selections.setText(QtGui.QApplication.translate("MainWindow", "Selected letters/words", None, QtGui.QApplication.UnicodeUTF8))
        self.action_click_distribution.setText(QtGui.QApplication.translate("MainWindow", "Click distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.action_best_words.setText(QtGui.QApplication.translate("MainWindow", "Most probable words", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_letter_likelihoods.setText(QtGui.QApplication.translate("MainWindow", "Letter likelhoods", None, QtGui.QApplication.UnicodeUTF8))
        self.action_minimum_view.setText(QtGui.QApplication.translate("MainWindow", "Show minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.action_dictionary.setText(QtGui.QApplication.translate("MainWindow", "Dictionary", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_close.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.action_alphabet.setText(QtGui.QApplication.translate("MainWindow", "Alphabet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionB.setText(QtGui.QApplication.translate("MainWindow", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.action_volume.setText(QtGui.QApplication.translate("MainWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.action_space_bar.setText(QtGui.QApplication.translate("MainWindow", "Space bar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_port.setText(QtGui.QApplication.translate("MainWindow", "Port 20320", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about_ticker.setText(QtGui.QApplication.translate("MainWindow", "About Ticker", None, QtGui.QApplication.UnicodeUTF8))
        self.action_clear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.action_calibrate.setText(QtGui.QApplication.translate("MainWindow", "Calibrate (\"yes_\")", None, QtGui.QApplication.UnicodeUTF8))
        self.action_practise.setText(QtGui.QApplication.translate("MainWindow", "Practise Clicks", None, QtGui.QApplication.UnicodeUTF8))
        self.action_tutorial.setText(QtGui.QApplication.translate("MainWindow", "Tutorial", None, QtGui.QApplication.UnicodeUTF8))
        self.action_inc_phrases.setText(QtGui.QApplication.translate("MainWindow", "Incremet Phrases", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fast_mode.setText(QtGui.QApplication.translate("MainWindow", "Fast Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.action_clear_2.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))

