# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'volume_layout.ui'
#
# Created: Tue Mar 26 12:40:36 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 285)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.volume_label_0 = QtGui.QLabel(Dialog)
        self.volume_label_0.setObjectName("volume_label_0")
        self.gridLayout.addWidget(self.volume_label_0, 2, 1, 1, 1)
        self.volume_label_1 = QtGui.QLabel(Dialog)
        self.volume_label_1.setObjectName("volume_label_1")
        self.gridLayout.addWidget(self.volume_label_1, 3, 1, 1, 1)
        self.volume_settings_1 = QtGui.QSlider(Dialog)
        self.volume_settings_1.setMinimum(1)
        self.volume_settings_1.setMaximum(1000)
        self.volume_settings_1.setProperty("value", 802)
        self.volume_settings_1.setSliderPosition(802)
        self.volume_settings_1.setOrientation(QtCore.Qt.Horizontal)
        self.volume_settings_1.setObjectName("volume_settings_1")
        self.gridLayout.addWidget(self.volume_settings_1, 3, 2, 1, 1)
        self.volume_label_2 = QtGui.QLabel(Dialog)
        self.volume_label_2.setObjectName("volume_label_2")
        self.gridLayout.addWidget(self.volume_label_2, 4, 1, 1, 1)
        self.volume_settings_2 = QtGui.QSlider(Dialog)
        self.volume_settings_2.setMinimum(1)
        self.volume_settings_2.setMaximum(1000)
        self.volume_settings_2.setProperty("value", 1000)
        self.volume_settings_2.setOrientation(QtCore.Qt.Horizontal)
        self.volume_settings_2.setObjectName("volume_settings_2")
        self.gridLayout.addWidget(self.volume_settings_2, 4, 2, 1, 1)
        self.volume_label_3 = QtGui.QLabel(Dialog)
        self.volume_label_3.setObjectName("volume_label_3")
        self.gridLayout.addWidget(self.volume_label_3, 5, 1, 1, 1)
        self.volume_settings_3 = QtGui.QSlider(Dialog)
        self.volume_settings_3.setMinimum(1)
        self.volume_settings_3.setMaximum(1000)
        self.volume_settings_3.setProperty("value", 800)
        self.volume_settings_3.setOrientation(QtCore.Qt.Horizontal)
        self.volume_settings_3.setObjectName("volume_settings_3")
        self.gridLayout.addWidget(self.volume_settings_3, 5, 2, 1, 1)
        self.volume_label_4 = QtGui.QLabel(Dialog)
        self.volume_label_4.setObjectName("volume_label_4")
        self.gridLayout.addWidget(self.volume_label_4, 6, 1, 1, 1)
        self.volume_settings_4 = QtGui.QSlider(Dialog)
        self.volume_settings_4.setMinimum(1)
        self.volume_settings_4.setMaximum(1000)
        self.volume_settings_4.setPageStep(12)
        self.volume_settings_4.setProperty("value", 700)
        self.volume_settings_4.setOrientation(QtCore.Qt.Horizontal)
        self.volume_settings_4.setObjectName("volume_settings_4")
        self.gridLayout.addWidget(self.volume_settings_4, 6, 2, 1, 1)
        self.volume_settings_0 = QtGui.QSlider(Dialog)
        self.volume_settings_0.setMinimum(1)
        self.volume_settings_0.setMaximum(1000)
        self.volume_settings_0.setProperty("value", 702)
        self.volume_settings_0.setSliderPosition(702)
        self.volume_settings_0.setOrientation(QtCore.Qt.Horizontal)
        self.volume_settings_0.setObjectName("volume_settings_0")
        self.gridLayout.addWidget(self.volume_settings_0, 2, 2, 1, 1)
        self.box_mute_0 = QtGui.QCheckBox(Dialog)
        self.box_mute_0.setObjectName("box_mute_0")
        self.gridLayout.addWidget(self.box_mute_0, 2, 3, 1, 1)
        self.box_mute_1 = QtGui.QCheckBox(Dialog)
        self.box_mute_1.setObjectName("box_mute_1")
        self.gridLayout.addWidget(self.box_mute_1, 3, 3, 1, 1)
        self.box_mute_2 = QtGui.QCheckBox(Dialog)
        self.box_mute_2.setObjectName("box_mute_2")
        self.gridLayout.addWidget(self.box_mute_2, 4, 3, 1, 1)
        self.box_mute_3 = QtGui.QCheckBox(Dialog)
        self.box_mute_3.setObjectName("box_mute_3")
        self.gridLayout.addWidget(self.box_mute_3, 5, 3, 1, 1)
        self.box_mute_4 = QtGui.QCheckBox(Dialog)
        self.box_mute_4.setObjectName("box_mute_4")
        self.gridLayout.addWidget(self.box_mute_4, 6, 3, 1, 1)
        self.box_mute_all = QtGui.QCheckBox(Dialog)
        self.box_mute_all.setObjectName("box_mute_all")
        self.gridLayout.addWidget(self.box_mute_all, 0, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Volume Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_label_0.setText(QtGui.QApplication.translate("Dialog", "Cheerful Charlie", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_label_1.setText(QtGui.QApplication.translate("Dialog", "Sad Sandy", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_settings_1.setToolTip(QtGui.QApplication.translate("Dialog", "Adjust the volume of this voice", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_label_2.setText(QtGui.QApplication.translate("Dialog", "Bartitone Bob", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_settings_2.setToolTip(QtGui.QApplication.translate("Dialog", "Adjust the volume of this voice", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_label_3.setText(QtGui.QApplication.translate("Dialog", "Melodic Mary", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_settings_3.setToolTip(QtGui.QApplication.translate("Dialog", "Adjust the volume of this voice", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_label_4.setText(QtGui.QApplication.translate("Dialog", "Precise Pete", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_settings_4.setToolTip(QtGui.QApplication.translate("Dialog", "Adjust the volume of this voice", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_settings_0.setToolTip(QtGui.QApplication.translate("Dialog", "Adjust the volume of this voice", None, QtGui.QApplication.UnicodeUTF8))
        self.box_mute_0.setText(QtGui.QApplication.translate("Dialog", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.box_mute_1.setText(QtGui.QApplication.translate("Dialog", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.box_mute_2.setText(QtGui.QApplication.translate("Dialog", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.box_mute_3.setText(QtGui.QApplication.translate("Dialog", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.box_mute_4.setText(QtGui.QApplication.translate("Dialog", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.box_mute_all.setText(QtGui.QApplication.translate("Dialog", "Mute all", None, QtGui.QApplication.UnicodeUTF8))

